# **Finding the best Model fo this Problem**

Importing necessary libraries

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

In [3]:
import warnings
warnings.filterwarnings("ignore")

Calling the data from the path

In [4]:
data = pd.read_csv(r"/root/MLOPS_PROJEST_WSL/Airline-Passenger-Satisfaction/project/notebooks/processed_data.csv")
data.head(5)

Unnamed: 0  Gender  Age  Customer Type  Type of Travel  Class  \
0           0       1   48              0               0      0   
1           1       0   35              1               0      0   
2           2       1   41              1               0      0   
3           3       1   50              1               0      0   
4           4       0   49              1               0      0   

   Flight Distance  Departure Delay  Arrival Delay  \
0                1                2              2   
1                1                3              3   
2                2                0              0   
3                3                0              0   
4                3                0              2   

   Departure and Arrival Time Convenience  Satisfaction_Label  \
0                                       3                   0   
1                                       2                   1   
2                                       4                   1   
3                                       2                   1   
4                                       3                   1   

   flight_service_1  flight_service_2  flight_service_3  
0              3.33               4.0              4.50  
1              3.33               4.4              4.25  
2              4.33               4.2              3.25  
3              3.00               4.6              4.25  
4              3.67               4.0              3.00

Dividing the data into target and features in seperate variables

In [5]:
X = data.drop(columns=["Satisfaction_Label"], axis=1)
y = data["Satisfaction_Label"]

Spliting data 

In [6]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the training and testing sets
X_train.shape, X_test.shape  # Shows the shapes of training and testing sets


((103904, 13), (25976, 13))

Creating an function to check evaluation of model

In [7]:
def evaluate_model(true, pred):
    # Calculate accuracy using true labels and predicted labels
    accuracy = accuracy_score(true, pred)
    
    # Generate confusion matrix using true labels and predicted labels
    confusion_matrix_result = confusion_matrix(true, pred)
    
    # Calculate ROC AUC score using true labels and predicted labels
    roc_auc = roc_auc_score(true, pred)
    
    # Return the calculated metrics: accuracy, confusion matrix, and ROC AUC score
    return accuracy, confusion_matrix_result, roc_auc


In [16]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score

# Assuming X_train, X_test, y_train, y_test are already defined

model = {
    "LogisticRegression": LogisticRegression(),
    "RidgeClassifier": RidgeClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "AdaBoostClassifier": AdaBoostClassifier(),
    "KNeighborsClassifier": KNeighborsClassifier(),
    "MultinomialNB": MultinomialNB(),
    # "SVC": SVC()
}

model_list = []
accuracy_list = []

for model_name, model_instant in model.items():
    # Train each model
    model_instant.fit(X_train, y_train)

    # Predict on training and testing sets
    y_train_pred = model_instant.predict(X_train)
    y_test_pred = model_instant.predict(X_test)

    # Evaluate model performance on training set
    model_train_accuracy, model_train_confusion_matrix, model_train_roc_auc = evaluate_model(y_train, y_train_pred)
    
    # Evaluate model performance on testing set
    model_test_accuracy, model_test_confusion_matrix, model_test_roc_auc = evaluate_model(y_test, y_test_pred)

    model_list.append(model_name)

    # Display model performance for training set
    print(f"-----------{model_name}-----------")
    print("Model performance on training set")
    print(f"accuracy_score : {(model_train_accuracy).round(2)}")
    print(f"confusion_matrix :\n {(model_train_confusion_matrix).round(2)}")
    print(f"roc_auc : {(model_train_roc_auc).round(2)}")

    # Display model performance for testing set
    print("Model performance on testing set")
    print(f"accuracy_score : {(model_test_accuracy).round(2)}")
    print(f"confusion_matrix :\n {(model_test_confusion_matrix).round(2)}")
    print(f"roc_auc : {(model_test_roc_auc).round(2)}")
    print("\n")

    accuracy_list.append(model_test_accuracy)


-----------LogisticRegression-----------
Model performance on training set
accuracy_score : 0.57
confusion_matrix :
 [[58729     0]
 [45175     0]]
roc_auc : 0.5
Model performance on testing set
accuracy_score : 0.57
confusion_matrix :
 [[14723     0]
 [11253     0]]
roc_auc : 0.5


-----------RidgeClassifier-----------
Model performance on training set
accuracy_score : 0.86
confusion_matrix :
 [[51804  6925]
 [ 7592 37583]]
roc_auc : 0.86
Model performance on testing set
accuracy_score : 0.86
confusion_matrix :
 [[12984  1739]
 [ 1846  9407]]
roc_auc : 0.86


-----------RandomForestClassifier-----------
Model performance on training set
accuracy_score : 1.0
confusion_matrix :
 [[58727     2]
 [    3 45172]]
roc_auc : 1.0
Model performance on testing set
accuracy_score : 0.92
confusion_matrix :
 [[14015   708]
 [ 1408  9845]]
roc_auc : 0.91


-----------AdaBoostClassifier-----------
Model performance on training set
accuracy_score : 0.88
confusion_matrix :
 [[52651  6078]
 [ 6292 38883

In [17]:
pd.DataFrame(list(zip(model_list, accuracy_list)), columns=["Model_Name", "Accuracy_Score"]).sort_values(by=["Accuracy_Score"], ascending=False)

Model_Name  Accuracy_Score
2  RandomForestClassifier        0.918540
3      AdaBoostClassifier        0.879196
1         RidgeClassifier        0.861988
4    KNeighborsClassifier        0.676201
5           MultinomialNB        0.657607
0      LogisticRegression        0.566792

In [19]:
model = RandomForestClassifier()  # Initializing RandomForestClassifier
model.fit(X_train, y_train)  # Fitting the model to the training data
y_pred = model.predict(X_test)  # Predicting on the test set
score = accuracy_score(y_test, y_pred) * 100  # Calculating accuracy
print("Accuracy : {:.1f}".format(score))  # Printing the accuracy score

Accuracy : 91.9


**The RandomForestClassifier demonstrates high accuracy on both training and testing sets, with minimal misclassifications (as seen in the confusion matrix) and a robust ROC AUC score, indicating strong discriminatory power between classes.**